@startuml
!include .\\Program.puml
!include .\\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\obj\Debug\net6.0\Assignment 04.AssemblyInfo.puml
!include .\\obj\Debug\net6.0\Assignment 04.GlobalUsings.g.puml
@enduml
